project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "Willing Consulting"
  site-url: "https://willingconsulting.com"
  description: "Carol Willing, Human Centered Open Source Leadership"
  favicon: static/images/wave-connecting-250.png
  page-navigation: true
  back-to-top-navigation: true
  cookie-consent: true
  google-analytics: "G-HMME8QVYFL"
  open-graph: true
  twitter-card:
    creator: "@WillingCarol"
  repo-url: https://github.com/willingc/willing-consulting-2022
  issue-url: https://github.com/willingc/willing-consulting-2022/issues/new
  repo-branch: main
  repo-actions: [edit, issue]

  navbar:
    background: "#FFFFFF"
    logo: images/logo-horizontal-500-250.png
    logo-alt: Willing Consulting
    title: false
    search: true
    collapse-below: lg
    left:
      - text: Home
        aria-label: home
        href: index.qmd
        icon: house-door-fill
      - href: about.qmd
        text: About
        aria-label: "About me"
      - href: speaking.qmd
        text: Speaking
        aria-label: "Speaking and Invited Talks"
      - href: blog/index.qmd
        text: Blog
        aria-label: "My Blog"
      - href: til/index.qmd
        text: TIL
        aria-label: "Today I Learned"
      - href: pysplashlive.qmd
        text: PySplashLive
        aria-label: "pysplashlive"
      - href: contact.qmd
        text: Contact
        aria-label: "Contact"
    right:
      - icon: github
        href: https://github.com/willingc
        aria-label: Carol Willing on GitHub
      

  page-footer:
    background: "#FFFFFF"
    left: 2013-2024, Carol Willing.
    right: Built with <a href="https://quarto.org/">Quarto</a>.
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/carolwilling/
        aria-label: Carol Willing on LinkedIn
      - icon: mastodon
        href: https://hachyderm.io/web/@willingc
        aria-label: Carol Willing on Mastodon
      - icon: rss
        href: index.xml
        aria-label: Carol Willing Blog RSS
      - icon: speakerdeck
        href: https://speakerdeck.com/willingc
        aria-label: Carol Willing Speaker Deck

format:
  html:
    theme: [simplex, assets/wilcon.scss]
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5em
    html-math-method:
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js.min
    lightbox: true
    callout-appearance: simple
