project:
  type: website
  output-dir: _site

website:
  title: "Willing Consulting"
  favicon: static/images/wave-connecting-250.png
  open-graph: true
  twitter-card:
    creator: "@WillingCarol"
  site-url: "https://willingconsulting.com/"
  description: "Human Centered Open Source Leadership"
  repo-url: https://github.com/willingc/willing-consulting-2022
  repo-branch: main
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Copyright: 2013-2023, Carol Willing.
    center: 
      - icon: github
        href: https://github.com/willingc
      - icon: linkedin
        href: https://www.linkedin.com/in/carolwilling/
      - icon: twitter
        href: https://twitter.com/WillingCarol
      - icon: rss
        href: index.xml
    right: |
      This site was built with <a href="https://quarto.org/">Quarto</a>.
  navbar:
    background: "#f8f9fa"
    search: true
    left:
      - text: Home
        aria-label: home
        href: index.qmd
      - text: About
        aria-label: about
        menu:
          - about.md
          - about-award.qmd
          - about-press.qmd
          - about-podcasts.qmd
      - href: speaking.md
        text: Speaking
        aria-label: speaking
      - href: blog/index.qmd
        text: Blog
        aria-label: blog
      - href: til/index.qmd
        text: TIL
        aria-label: til
      - href: contact.md
        text: Contact
        aria-label: contact
    tools:
      - icon: github
        href: https://github.com/willingc
      - icon: linkedin
        href: https://www.linkedin.com/in/carolwilling/
      - icon: twitter
        href: https://twitter.com/WillingCarol
      - icon: rss
        href: index.xml
execute:
  freeze: auto
format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
