project:
  type: website

website:
  title: "Willing Consulting"
  favicon: static/images/favicon_symbol.png
  open-graph: true
  twitter-card:
    creator: "@WillingCarol"
  site-url: "https://willingconsulting.com/"
  description: "Human Centered Open Source Leadership"
  repo-url: https://github.com/willingc/willing-consulting-2022
  navbar:
    background: primary
    search: true
    left:
      - href: index.md
        text: Home
      - href: about.md
        text: About
      - href: speaking.md
        text: Speaking
      - href: contact.md
        text: Contact
    tools:
      - icon: github
        href: https://github.com/willingc
      - icon: linkedin
        href: https://www.linkedin.com/in/carolwilling/
      - icon: twitter
        href: https://twitter.com/WillingCarol
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: lightly
      dark: darkly
    toc: true
