project:
  type: website

execute:
  freeze: auto

language:
  search-text-placeholder: Search

website:
  title: "Willing Consulting"
  site-url: "https://willingconsulting.com"
  description: "Carol Willing, Human Centered Open Source Leadership"
  favicon: static/images/wave-connecting-250.png
  page-navigation: true
  back-to-top-navigation: true
  google-analytics:
    tracking-id: "G-HMME8QVYFL"
    storage: none
  open-graph: true
  plausible-analytics: { path: _plausible_snippet.html }
  twitter-card:
    creator: "@WillingCarol"
  search:
    location: navbar
    type: textbox
  navbar:
    logo: images/willing-horizontal-320-77.png
    logo-alt: Willing Consulting
    title: false
    collapse-below: lg
    left:
      - text: Home
        aria-label: home
        href: index.qmd
        icon: house-door-fill
      - text: "About"
        menu:
        - href: about.qmd
          text: About Carol
          aria-label: "About"
        - href: about/about-award.qmd
          text: Awards
          aria-label: "Awards"
        - href: about/about-bios.qmd
          text: Bios
          aria-label: "Bios"
        - href: about/about-podcasts.qmd
          text: Podcasts
          aria-label: "Podcasts"
        - href: about/about-press.qmd
          text: Press
          aria-label: "Press"
      - href: speaking.qmd
        text: Speaking
        aria-label: "Speaking and Invited Talks"
      - href: blog/index.qmd
        text: Blog
        aria-label: "My Blog"
      - href: til/index.qmd
        text: TIL
        aria-label: "Today I Learned"
      - href: pysplashlive.qmd
        text: PySplashLive
        aria-label: "pysplashlive"
      - href: contact.qmd
        text: Contact
        aria-label: "Contact"
    right:
      - icon: github
        href: https://github.com/willingc
        aria-label: Carol Willing on GitHub
  page-footer:
    left: 2013-2024, Carol Willing.
    right: Built with <a href="https://quarto.org/">Quarto</a>.
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/carolwilling/
        aria-label: Carol Willing on LinkedIn
      - icon: mastodon
        href: https://hachyderm.io/web/@willingc
        aria-label: Carol Willing on Mastodon
      - href: https://bsky.app/profile/willingc.bsky.social
        text: "{{< iconify simple-icons bluesky >}}"
        aria-label: Carol Willing on Bluesky
      - icon: rss
        href: index.xml
        aria-label: Carol Willing Blog RSS
  announcement:
    icon: globe
    dismissable: false
    content: "Willing Consulting is a proud, three-year **Partner Sponsor of [PyLadiesCon](https://2025.conference.pyladies.com/en/)**. Join us online December 5-7, 2025. Registration is free."
    type: danger
    position: below-navbar

format:
  html:
    theme: [simplex, wilcon.scss]
    css: styles.css
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5em
    lightbox: true
    callout-appearance: simple

esbuild:
  bundle: true
  minify: true
  sourcemap: true
