project:
  type: website
  output-dir: _site

website:
  title: "Willing Consulting"
  image: images/logo-horizontal-1000.png
  favicon: static/images/wave-connecting-250.png
  cookie-consent: true
  google-analytics: "G-HMME8QVYFL"
  open-graph: true
  twitter-card:
    creator: "@WillingCarol"
  site-url: "https://willingconsulting.com"
  description: "Human Centered Open Source Leadership"
  repo-url: https://github.com/willingc/willing-consulting-2022
  issue-url: https://github.com/willingc/willing-consulting-2022/issues/new
  repo-branch: main
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer:
    left: |
      Copyright: 2013-2024, Carol Willing.
    center:
      - icon: github
        href: https://github.com/willingc
        aria-label: Williingc on Github
      - icon: linkedin
        href: https://www.linkedin.com/in/carolwilling/
        aria-label: Carol Willing on LinkedIn
      - icon: twitter
        href: https://twitter.com/WillingCarol
        aria-label: WillingCarol on Twitter
      - icon: rss
        href: index.xml
        aria-label: Carol Willing Blog RSS
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>.
  navbar:
    logo: images/logo-horizontal-500-250.png
    logo-alt: Willing Consulting
    title: false
    search: true
    collapse-below: lg
    left:
      - text: Home
        aria-label: home
        href: index.qmd
        icon: house-door-fill
      - text: About
        href: about.qmd
        aria-label: about
      - href: speaking.qmd
        text: Speaking
        aria-label: speaking
      - href: blog/index.qmd
        text: Blog
        aria-label: blog
      - href: til/index.qmd
        text: TIL
        aria-label: til
      - href: pysplashlive.qmd
        text: PySplashLive
        aria-label: pysplashlive
      - href: contact.qmd
        text: Contact
        aria-label: contact
    tools: 
      - icon: github
        href: https://github.com/willingc
        aria-label: Carol Willing on GitHub
format:
  html:
    theme:
      light: [cosmo]
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 800px
      margin-width: 250px
    html-math-method:
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js.min
    lightbox: true

execute: 
  freeze: auto