site_name: Willing Consulting
docs_dir: docs

copyright: Copyright &copy; 2013 - 2022 Carol Willing. All rights reserved.

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon_symbol.png

  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

extra_css:
  - static/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/carolwilling
    - icon: fontawesome/brands/github
      link: https://github.com/willingc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/playlist?list=PLbmHuawY0ITI8crhYoMMi2xiZiKQuxMEj
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WillingCarol

nav:
  - Home: index.md
  - About: about.md
  - Speaking: speaking.md
  - Contact: contact.md
  - Blog: 
    - blog/index.md
    - 2019:
      - blog/posts/2019/2019-11-02-python-steering-retro.md
      - blog/posts/2019/2019-09-19-python-beta.md
      - blog/posts/2019/2019-07-01-locations-and-git.md
    - 2018:
      - blog/posts/2018/2018-08-09-sunrise-semester.md
      - blog/posts/2018/2018-09-30-getting-started.md
      - blog/posts/2018/2018-10-01-jupyter-ipython.md
    - 2017:
      - blog/posts/2017/2017-06-04-snakes-planets.md
    - 2015:
      - blog/posts/2015/2015-01-21-music-data-science-and-community-poster-at-pycon-2014.md
      - blog/posts/2015/2015-02-03-i-am-not-a-tree.md
      - blog/posts/2015/2015-02-18-decorators-visualized.md
      - blog/posts/2015/2015-03-02-security-at-the-seams.md
      - blog/posts/2015/2015-03-04-building-a-better-community.md
      - blog/posts/2015/2015-03-18-mentor-music-and-motivation.md
      - blog/posts/2015/2015-06-03-play-it-again-pyvideo-org.md
      - blog/posts/2015/2015-06-09-mission-moment-hammond.md
      - blog/posts/2015/2015-08-04-change-community-compassion.md
      - blog/posts/2015/2015-08-09-whats-a-fab-lab.md
    - 2014:
      - blog/posts/2014/2014-02-07-weekend-wisdom-python.md
      - blog/posts/2014/2014-02-07-what-can-you-do-in-8-minutes-the-importance-of-allies-in-advocacy.md
      - blog/posts/2014/2014-02-18-two-django-licious-scoops.md
      - blog/posts/2014/2014-03-01-saturday-sharing-some-git-goodness.md
      - blog/posts/2014/2014-03-03-monday-mention-newcomers-to-open-source-development.md
      - blog/posts/2014/2014-06-07-security-and-cryptography-gems.md
      - blog/posts/2014/2014-07-14-scipy-2014-a-mother-and-daughter-share-creativity-computer-science-and-communication.md
    - 2013:
      - blog/posts/2013/2013-02-05-using-senses-to-guide-yourself-through-the-fog.md
      - blog/posts/2013/2013-02-10-sharing-the-knowledge.md
      - blog/posts/2013/2013-03-08-intwomen2013.md
      - blog/posts/2013/2013-03-15-xblock.md
      - blog/posts/2013/2013-03-18-moving-forward-monday-the-ada-initiative.md
      - blog/posts/2013/2013-08-12-moving-forward-monday-mom.md
      - blog/posts/2013/2013-08-13-earn-mitocw.md
      - blog/posts/2013/2013-08-19-moving-forward-monday-meaningful-mindful-mental-health-resources.md
      - blog/posts/2013/2013-08-24-ww-allen-bradley.md
      - blog/posts/2013/2013-09-24-tealeaves.md
      - blog/posts/2013/2013-09-29-weekend-whimsy-string-theory-the-hics-and-candy-chang.md
      - blog/posts/2013/2013-12-22-inkscapefaq.md
