site_name: Willing Consulting
site_url: https://willingconsulting.com
site_author: Carol Willing
site_description: >-
  Learn. Build. Share.
# repo_name: willing-consulting-2022
# repo_url: https://github.com/willingc/willing-consulting-2022
# edit_uri: ''
copyright: Copyright &copy; 2013 - 2022 Carol Willing. All rights reserved.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
      # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon_symbol.png
  logo: assets/images/wallpaper_symbol.png
plugins:
  - blog:
      blog_dir: blog
      post_date_format: long
      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      pagination: true
      pagination_per_page: 5
      authors: true
      authors_file: blog/.authors.yml
      categories_allowed:
        - General
        - People
        - Tech
  - search
  - tags:
      tags_file: blog/tags.md
nav:
  - index.md
  - About: about.md
  - Services:
      - services/development.md
      - services/training.md
      - services/workshops.md
  - Speaking: speaking.md
  - Contact: contact.md
  - Blog:
      - blog/index.md
      - blog/tags.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/carolwilling
    - icon: fontawesome/brands/github
      link: https://github.com/willingc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/playlist?list=PLbmHuawY0ITI8crhYoMMi2xiZiKQuxMEj
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WillingCarol
