name: Accessibility Scanner
on: workflow_dispatch

jobs:
  accessibility_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-scanner@v2
        with:
          urls: | # Provide a newline-delimited list of URLs to scan; more information below.
            "https://willingconsulting.com"
          repository: "willingc/willing-consulting-2022" # Provide a repository name-with-owner (in the format "primer/primer-docs"). This is where issues will be filed and where Copilot will open PRs; more information below.
          token: ${{ secrets.GH_TOKEN }} # This token must have write access to the repo above (contents, issues, and PRs); more information below. Note: GitHub Actions' GITHUB_TOKEN cannot be used here.
          cache_key: willingconsulting # Provide a filename that will be used when caching results. We recommend including the name or domain of the site being scanned.
          # login_url: # Optional: URL of the login page if authentication is required
          # username: # Optional: Username for authentication
          # password: ${{ secrets.PASSWORD }} # Optional: Password for authentication (use secrets!)
          # auth_context: # Optional: Stringified JSON object for complex authentication
          # skip_copilot_assignment: false # Optional: Set to true to skip assigning issues to GitHub Copilot (or if you don't have GitHub Copilot)
          # include_screenshots: false # Optional: Set to true to capture screenshots and include links to them in filed issues
          # open_grouped_issues: false # Optional: Set to true to open an issue grouping individual issues per violation
          # reduced_motion: no-preference # Optional: Playwright reduced motion configuration option
          # color_scheme: light # Optional: Playwright color scheme configuration option
