on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@10ecffe43941bc1d1ea080631818c4aa70ee0435 # v2
        with:
          version: 1.10.18

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@91dabb203fce7f899d10ef8e482d94b00f397cbc # v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
